### ISSUE TITLE
stable diffusion

### ISSUE THREAD

**Issue by AlexanderKozhevin** [graphcore/tutorials#11]
Is there any template for stable diffusion 1.5 inference?

By the way, is there discord chat?

**Comment by payoto** [comment]
You can find our latest stable diffusion examples in the `optimum-graphcore` repository:

https://github.com/huggingface/optimum-graphcore/tree/main/notebooks/stable_diffusion

It includes v1.5 and v2. I think it might also work with openjourney checkpoints but we don't test that one regularly.

We don't have a discord but we have a community slack channel https://join.slack.com/t/graphcorecommunity/shared_invite/zt-1lobvjddh-HB7bKsqihaEwaPF~lP7XBw if you would like to join it
