### ISSUE TITLE
how to visualizes graph, for example?

### ISSUE THREAD

**Issue by daixiangzi** [graphcore/tutorials#8]
![](https://www.graphcore.ai/hubfs/images/ligo_zoom_logo.png)

**Comment by daixiangzi** [comment]
![image](https://user-images.githubusercontent.com/24811131/154016149-6221b78b-562d-4f11-993b-dc411b77c885.png)

**Comment by LRVerkin** [comment]
Hi daixiangzi, unfortunately Graphcore does not share the code used to generate these figures.
