### ISSUE TITLE
Bert training code with packedBERT

### ISSUE THREAD

**Issue by SeaOfOcean** [graphcore/tutorials#9]
Hi

The packedBERT https://github.com/graphcore/tutorials/tree/master/blogs_code/packedBERT seems promising solution for tasks with variable length inputs. Could you provide training code for bert with packed dataset?

Thanks

**Comment by ManueleSigona** [comment]
Hi @SeaOfOcean,

apologies for the delay in getting back to you. The training code for BERT with the packed dataset can be found in the [PopART BERT example](https://github.com/graphcore/examples/tree/master/nlp/bert/popart). The [README in bert_data](https://github.com/graphcore/examples/tree/master/nlp/bert/popart/bert_data) shows in step 5 how to prepare the packed dataset, and you can find packed configurations to use for training in [configs/packed](https://github.com/graphcore/examples/tree/master/nlp/bert/popart/configs/packed).

Let us know if you encounter any issues with the code. Thank you.

Manuele
Graphcore
